extends: airbnb
parser: babel-eslint

# env:
#   browser: true

# globals:
#   __DEV__: true
#   React: true

plugins: [babel]

rules:
  # too many requires to bother disabling per-line
  global-require: 0
  # same as airbnb, just 80 chars instead of 100
  max-len: [2, 80, 2, { ignoreUrls: true, ignoreComments: false }]
  # apparently, x.y[0].z counts as a 4-level chain...
  newline-per-chained-call: [2, { ignoreChainWithDepth: 4 }]
  # until the custom confirm is here
  no-alert: 0
  # it's node
  no-console: 0
  # yeah, no
  no-continue: 0
  # doesn't allow mutating arguments otherwise
  no-param-reassign: [2, { props: false }]
  # just my preference
  no-underscore-dangle: 0
  # doesn't allow 'a && !b && doStuff();' otherwise
  no-unused-expressions: [2, { allowShortCircuit: true }]

  generator-star-spacing: 0
  babel/generator-star-spacing: 1
